:api_key: f517b9765ba460831196163653a12fcf
:ignore_files:
- todo
- config/settings_data.json
development:
  password: ccde88a29a0da625f19c1905c693f043
  theme_id: "129547073"
  store: github-deploy-test.myshopify.com
production:
  password: 9a91f325de49da9b8bbfe31f64c0ee15
  theme_id: "129546689"
  store: github-deploy-test.myshopify.com
  timeout: 60s
